# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/lc3_bram/lc3_bram.srcs/sources_1/ip/dual_mem/dual_mem.xci
# IP: The module: 'dual_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/lc3_bram/lc3_bram.srcs/sources_1/ip/dual_mem/dual_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dual_mem'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/lc3_bram/lc3_bram.srcs/sources_1/ip/dual_mem/dual_mem.xci
# IP: The module: 'dual_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/lc3_bram/lc3_bram.srcs/sources_1/ip/dual_mem/dual_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dual_mem'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
